FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

RUN apt update && \
    apt install -y ffmpeg python3-pip && \
    apt clean all && \
    rm -rf /var/lib/apt/lists/*

# 设置 Hugging Face 镜像源环境变量
ENV HF_ENDPOINT=https://hf-mirror.com

WORKDIR /app
COPY ./backend /app
RUN pip install --no-cache-dir -i https://pypi.mirrors.ustc.edu.cn/simple -r requirements.txt
RUN pip install --no-cache-dir -i https://pypi.mirrors.ustc.edu.cn/simple 'transformers[torch]>=4.23'

CMD ["python3", "main.py"]
